
---
title: "案例教学方法讲义"
author: "Gabe"
date:  '`r format(Sys.Date(), "%Y %B %d")`'
output:
  beamer_presentation:
    colortheme: lily
    latex_engine: xelatex
    slide_level: 2
    theme: default #Frankfurt
    toc: yes
    keep_tex: yes # 不加这条将读不了在线图形
  ioslides_presentation:
    incremental: yes
    slide_level: 3
    toc: yes
  pdf_document:
    keep_tex: yes
    latex_engine: xelatex #编译有中文的.rmd
    number_sections: yes
    toc: yes
mainfont: SimSun
monofont: Microsoft YaHei
header-includes:
- \usepackage{xeCJK}
- \linespread{1.3}\selectfont
# - \usepackage{fancyhdr}
# - \pagestyle{fancy}
# - \fancyhead[CO,CE]{This is fancy header}
# - \fancyfoot[CO,CE]{And this is a fancy footer}
# - \fancyfoot[LE,RO]{\thepage}
sansfont: Microsoft YaHei
fontsize: 12pt
bibliography: test.bib
---


# 什么是案例教学法

## 案例教学法的理念

* 教育不仅是教导学习者成为会做事的技术人员(technician)，更重要的是要教导他们思考的方法，学习表达个人的想法；
* 学习者须具备运用学得的概念与资讯以支持个人论点，或反驳、挑战他人观点的能力
* 提升个人倾听和沟通的能力，展现尊重他人的民主风范；
* 藉由群体思考，促使个人的观点获得既深且广的发展；

----

* 针对问题设想可能的解决之道，藉由分析预测每个行动可能产生的结果，作最佳的决策；
* 增进个人反思能力，于行动之后，能检视个人决策的结果，自我修正
* 案例教学法的教育理念，不是培养理论专家，而是培养活用理论的实践家，以及具备
  反思能力的决策者。

# 案例教学法的特质

## 案例教学法是以“案例”为教学工具

* 透过深度的讨论活动，汲引出学习者既有的经验和知识，藉由认知冲突，促使学习者反思影响个人行动(action)之隐而未现的信念与价值观，在分析、辩护及反思中建构知识，因为认知的发展源自于个人有意义的经验。
* 并不在学习前提供学习者大量的理论性知识，而是在探究案例的活动中，提供相关的
  资讯以协助学习者在探索案例中所产生的认知冲突，达到学习的目的

----

* 学习是一趟非线性的知性之旅，学习路径是一系列的相关经验，容许学习者重组个人的学习经验，重新赋予知识新的意义，并且不断地挑战学习者既有的认知模式与知识。

## 案例教学法着重学习的过程

* 强调以学习者为中心，重视学习者的学习主动性，而且学习历程充满了不确定性，是没有终点的教学学习循环
* 案例教学法藉由具有故事情节及人物刻画的案例描述，以及故事中所呈现的冲突，没有所谓的“标准答案”或是“愚蠢的问题”，每个学习者都有提问和回答问题的权利与责任

## 案例教学法不同于苏格拉底式问答法

* 问答法的讨论方向及最终目的是由教师事前订定的，具有相当程度的确定性，而前者则是在讨论过程中，由群体的思考决定。
* 在讨论过程中，教师的责任在于引导讨论，而非主导讨论，学习者、教师与案例间的互动结果才是主导讨论学习方向的关键，因此，参杂了一定程度的不确定因素，* 而且每一个问题的解决和每个行动的结果，都会导引出另一个学习问题，和另一个冲突议题
* 案例教学法是一教学学习循环

# 案例教学法的教育价值

## 教导“尊重”，促进群体思考，增强主动学习的动机

* 案例教学法鼓励将个人所学贡献给参与的人，学习者个人的观念是重要的资讯来源，每位学习者既有的经验和观念都受到应有的尊重，激发“主动参与”的动机
* 由于彼此的尊重、倾听和沟通，增进同侪团体的合作互动，群体思考技巧获得发展，
* 同时提升个人诠释和分析理论的能力、结合理论与实务的能力、解决问题的能力、和创新思考的能力

## 提升反思、批判思考、科学探究及问题解决能力
* 案例教学法乃以情境学习论、认知弹性论为基础，将概念嵌于案例本身所反映的实际情境中，提供学习者掌握情境脉络，分析处理复杂情境的学习机会，以弥补过度简化的理论推论，建构理论与实务之间的关连。
* 知识不是抽象的，而是包含在案例的情境、讨论者的经验中，藉由不断地探究和反思批判所形成具体方案

## 摆脱“唯一标准答案”的枷锁

* 案例教学法帮助学习者了解个人的决定及行动对于事件的影响，同时反思决策及行动决定的历程，体认面对两难困境时，并无绝对完美的解决之道，也无绝对的“标准答案
* 但是决策者必须为自己的决策及行动负责，促使学习者扬弃对“标准答案”的追求，
  提升学习者对于不确定和模糊不清的概念的忍受度

## 总结：案例教学法

* 案例教学法源自于医学教育的问题导向学习，是以学习者为中心的合作学习，跨学科
  领域的学习架构
* 强化学习者主动参与的学习行为，其中真实的问题帮助学习者将所学的内容与真实的
生活连结

----

* 在教学活动中，教师是引导者、协助者，而学习者是学习的主导者，因此，案例教学
法不仅影响学习者的学习，同时也影响教师的教学，促使教师思考学习者的学习、课程
的架构与组织、案例探究与教学内容的关连性、以及学科统整等问题
* 案例教学法被视为解决理论与实务间落差的利器，不仅可以传播新资讯，亦可激发学
  习者讨论与辩证的动机，可以培养学习者高层次的思考能力、问题解决的能力、评鉴
  能力及在情境脉络中的决策能力


# 案例的基本要素

## 好的“案例”要素
* 好的“案例”提供足够的讯息，能够引发多层次的讨论分析和行动，教导学习者批判分析，以及仔细规划行动的技巧。
* 所谓的“案例”是指，以故事描述(narrative)的手法，刻画真实人物在复杂的真实情境
  中，所面临的困境及必须采取的行动或决定

----

* 案例的内容源自于真实世界中人们所遭遇到问题，或是需要深入探究的重要议题，在本质上是跨领域的
* 案例的基本要素包括：丰富的情境描述、反映真实事件的故事情节(包含两难的情境、待解决的问题、危机的处理)，以及足够的相关资讯以供学习者思考及讨论

## 案例如同故事

* 撰写案例就如同撰写故事一般
* 必须有明确的主题、人物和情节，案例的铺陈必须如戏剧般地具有吸引力及剧情性，
* 包含人、事、时、地、物，反映社会或文化情境，具备适度的复杂性，及对多元观点
  的包容性，足以产生学习者认知冲突的要素，方能促使学习者养成主动学习及批判思
  考的推理能力，

----

* 案例中的人物和情节必须是取材自生活中的事件，具有真实性，而非小说般的虚构故事，情节的铺陈必须有真实感，但须采用匿名方式，以保护真实事件中的人物(Wassermann，1994)。
* 案例的素材可以是，以第一人称撰写亲身经历的个案报告(case reports)；或是以系统化的资料搜集技巧所获得之资料，经过分析整理后，以第三人称撰写的个案研究(case studies)。

## 案例要有研究问题

* 案例本身所提供的资讯(information)和资料(data)，必须涵盖重要的概念和议题，
* 且能与课程内容结合；具有思考性、检测性，足以呈现个人主观意识对于事件的影响，凸显不同观点之间的冲突性，引发学习者关切，赋予学习者自由选择权，使其可以自由检视，藉以激发学习者的思考
* 每个案例之后均应有研究问题，引导学习者在检视过程中，应用知识分析资料，提升
  对案例的瞭解，促使学习者提出解决方案，藉由讨论问题强调每个讨论阶段的重点，
  鼓励学习者将讨论内容与个人的经验结合，要求学习者为自己的论点提出合理的解释

## 组成(三部份组成)

> - 学习环境
- 提出问题
- 寻求答案

## 案例类型
- 信息式案例-------收集信息的形式
- 问题式案例-------以调查解决问题的能力为主
- 陈述式案例-------叙述一个事件的情境
- 决策式案例-------体现更多地解决问题
- 条例式案例-------把案例涉及的背景，问题，解决方法，评排列起来写出的案例。
- 实录式案例-------把实际发生的事件原原本本地记录下来，最后提出一系列供参考，讨论的问题。

# 案例教学组织

## 案例教学法的步骤

* 提供案例进行阅读、确认个案背景与融入情境、指派小组成员任务、小组进行讨论分析、小组分享讨论分析结果、评量成果。
* 教学者工作：
 - 选择或撰写案例，并对案例有充分的瞭解；
 - 规划案例教学进行步骤；
 - 瞭解学习者的程度与动机；

----

 - 扮演引导者的角色：
   - 在讨论过程中降低学生的困难度，避免学生因先被知识不
   - 足或缺乏经验而无法进行讨论；
   - 营造适于讨论的教学气氛；
   - 协助学生搜集资料，提供主要资料或至少要指出的资料方向；
   - 在学生讨论离题时，引导学生回到案例的情境中。

## 案例教学中老师的角色

* 不是我教你们什么东西，也不是我说什么东西，而是一个全班一起来讨论一个方案
* 教授的角色，不是专家，也不是教授，讲义就是问题,适当的时候问一个、两个问题，
  之后等你们回答出来
* 最好的案例教师，不要讲的太多。有一个传说，就是说一个资深的教授，他做一个非常好的案例教学一小时二十分钟，完全没有出过一次声
* 提前读这个方案，还有一个小组，五个人谈一谈这个方案



